@BASE_URL=http://localhost:8080

###
@resourceID = 1
GET {{BASE_URL}}/encyclopedia/resource/{{resourceID}} HTTP/1.1


###
GET {{BASE_URL}}/encyclopedia/resource/{{resourceID}}
?include=ResourceBase
&include=ProducedAt
&include=NeededFor
&include=NeededFor.ProducedFrom HTTP/1.1
