version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ComplexP@ssword1234
    ports:
      - 1433:1433
    container_name: mssqlserver
