USE SIMCOMPANIES
GO
SET IDENTITY_INSERT resource_base ON
INSERT INTO resource_base
    ([id], [name], [image], transportation, retailable, research, exchange_tradable, realm_available)
VALUES
    (1, 'Power', 'images/resources/power.png', 0, 0, 0, 1, 1),
    (2, 'Water', 'images/resources/water.png', 0, 0, 0, 1, 1),
    (3, 'Apples', 'images/resources/apples.png', 1, 1, 0, 1, 1),
    (4, 'Oranges', 'images/resources/oranges.png', 1, 1, 0, 1, 1),
    (5, 'Grapes', 'images/resources/grapes.png', 1, 1, 0, 1, 1),
    (6, 'Grain', 'images/resources/grain.png', 0.1, 0, 0, 1, 1),
    (7, 'Steak', 'images/resources/steak.png', 1, 1, 0, 1, 1),
    (8, 'Sausages', 'images/resources/sausages.png', 0.1, 1, 0, 1, 1),
    (9, 'Eggs', 'images/resources/eggs.png', 0.1, 1, 0, 1, 1),
    (10, 'Crude oil', 'images/resources/crude-oil.png', 1, 0, 0, 1, 1),
    (11, 'Petrol', 'images/resources/petrol.png', 1, 1, 0, 1, 1),
    (12, 'Diesel', 'images/resources/diesel.png', 1, 1, 0, 1, 1),
    (13, 'Transport', 'images/resources/transport.png', 0, 0, 0, 1, 1),
    (14, 'Minerals', 'images/resources/minerals.png', 1, 0, 0, 1, 1),
    (15, 'Bauxite', 'images/resources/bauxite.png', 1, 0, 0, 1, 1),
    (16, 'Silicon', 'images/resources/silicon.png', 1, 0, 0, 1, 1),
    (17, 'Chemicals', 'images/resources/chemicals.png', 1, 0, 0, 1, 1),
    (18, 'Aluminium', 'images/resources/aluminium.png', 1, 0, 0, 1, 1),
    (19, 'Plastic', 'images/resources/plastic.png', 1, 0, 0, 1, 1),
    (20, 'Processors', 'images/resources/processors.png', 1, 0, 0, 1, 1),
    (21, 'Electronic components', 'images/resources/electronic-components.png', 1, 0, 0, 1, 1),
    (22, 'Batteries', 'images/resources/batteries.png', 1, 0, 0, 1, 1),
    (23, 'Displays', 'images/resources/displays.png', 1, 0, 0, 1, 1),
    (24, 'Smart phones', 'images/resources/smart-phones.png', 2, 1, 0, 1, 1),
    (25, 'Tablets', 'images/resources/tablets.png', 2, 1, 0, 1, 1),
    (26, 'Laptops', 'images/resources/laptops.png', 2, 1, 0, 1, 1),
    (27, 'Monitors', 'images/resources/monitors.png', 2, 1, 0, 1, 1),
    (28, 'Televisions', 'images/resources/televisions.png', 2, 1, 0, 1, 1),
    (29, 'Plant research', 'images/resources/plant-research.png', 0, 0, 1, 1, 1),
    (30, 'Energy research', 'images/resources/energy-research.png', 0, 0, 1, 1, 1),
    (31, 'Mining research', 'images/resources/mining-research.png', 0, 0, 1, 1, 1),
    (32, 'Electronics research', 'images/resources/electronics-research.png', 0, 0, 1, 1, 1),
    (33, 'Breeding research', 'images/resources/breeding-research.png', 0, 0, 1, 1, 1),
    (34, 'Chemistry research', 'images/resources/chemistry-research.png', 0, 0, 1, 1, 1),
    (35, 'Software', 'images/resources/software.png', 0, 0, 1, 1, 1),
    (40, 'Cotton', 'images/resources/cotton.png', 0.5, 0, 0, 1, 1),
    (41, 'Fabric', 'images/resources/fabric.png', 0.5, 0, 0, 1, 1),
    (42, 'Iron ore', 'images/resources/iron-ore.png', 1, 0, 0, 1, 1),
    (43, 'Steel', 'images/resources/steel.png', 1, 0, 0, 1, 1),
    (44, 'Sand', 'images/resources/sand.png', 1, 0, 0, 1, 1),
    (45, 'Glass', 'images/resources/glass.png', 1, 0, 0, 1, 1),
    (46, 'Leather', 'images/resources/leather.png', 1, 0, 0, 1, 1),
    (47, 'On-board computer', 'images/resources/on-board-computer.png', 1, 0, 0, 1, 1),
    (48, 'Electric motor', 'images/resources/electric-motor.png', 2, 0, 0, 1, 1),
    (49, 'Luxury car interior', 'images/resources/luxury-car-interior.png', 2, 0, 0, 1, 1),
    (50, 'Basic interior', 'images/resources/car-interior.png', 2, 0, 0, 1, 1),
    (51, 'Car body', 'images/resources/car-body.png', 2, 0, 0, 1, 1),
    (52, 'Combustion engine', 'images/resources/combustion-engine.png', 2, 0, 0, 1, 1),
    (53, 'Economy e-car', 'images/resources/economy-e-car.png', 5, 1, 0, 1, 1),
    (54, 'Luxury e-car', 'images/resources/luxury-e-car.png', 5, 1, 0, 1, 1),
    (55, 'Economy car', 'images/resources/economy-car.png', 5, 1, 0, 1, 1),
    (56, 'Luxury car', 'images/resources/luxury-car.png', 5, 1, 0, 1, 1),
    (57, 'Truck', 'images/resources/truck.png', 5, 1, 0, 1, 1),
    (58, 'Automotive research', 'images/resources/automotive-research.png', 0, 0, 1, 1, 1),
    (59, 'Fashion research', 'images/resources/fashion-research.png', 0, 0, 1, 1, 1),
    (60, 'Underwear', 'images/resources/underwear.png', 1, 1, 0, 1, 1),
    (61, 'Gloves', 'images/resources/gloves.png', 1, 1, 0, 1, 1),
    (62, 'Dress', 'images/resources/dress.png', 1, 1, 0, 1, 1),
    (63, 'Stiletto Heel', 'images/resources/simmi-shoes.png', 1, 1, 0, 1, 1),
    (64, 'Handbags', 'images/resources/handbags.png', 1, 1, 0, 1, 1),
    (65, 'Sneakers', 'images/resources/sneakers.png', 1, 1, 0, 1, 1),
    (66, 'Seeds', 'images/resources/seeds.png', 0.1, 0, 0, 1, 1),
    (67, 'Xmas crackers', 'images/resources/xmas-crackers.png', 0.5, 1, 0, 1, 0),
    (68, 'Gold ore', 'images/resources/gold-ore.png', 10, 0, 0, 1, 1),
    (69, 'Golden bars', 'images/resources/golden-bars.png', 1000, 0, 0, 1, 1),
    (70, 'Luxury watch', 'images/resources/gold-watch.png', 1, 1, 0, 1, 1),
    (71, 'Necklace', 'images/resources/necklace.png', 1, 1, 0, 1, 1),
    (72, 'Sugarcane', 'images/resources/sugarcane.png', 0.1, 0, 0, 1, 1),
    (73, 'Ethanol', 'images/resources/ethanol.png', 1, 0, 0, 1, 1),
    (74, 'Methane', 'images/resources/methane.png', 1, 0, 0, 1, 1),
    (75, 'Carbon fibers', 'images/resources/carbon-fiber.png', 0.1, 0, 0, 1, 1),
    (76, 'Carbon composite', 'images/resources/carbon-composite.png', 1, 0, 0, 1, 1),
    (77, 'Fuselage', 'images/resources/fuselage.png', 2, 0, 0, 1, 1),
    (78, 'Wing', 'images/resources/wing.png', 2, 0, 0, 1, 1),
    (79, 'High grade e-comps', 'images/resources/high-grade-e-components.png', 1, 0, 0, 1, 1),
    (80, 'Flight computer', 'images/resources/flight-computer.png', 1, 0, 0, 1, 1),
    (81, 'Cockpit', 'images/resources/cockpit.png', 1, 0, 0, 1, 1),
    (82, 'Attitude control', 'images/resources/attitude-control.png', 1, 0, 0, 1, 1),
    (83, 'Rocket fuel', 'images/resources/rocket-fuel.png', 1, 0, 0, 1, 1),
    (84, 'Propellant tank', 'images/resources/fuel-tank.png', 1, 0, 0, 1, 1),
    (85, 'Solid fuel booster', 'images/resources/solid-rocket.png', 1, 0, 0, 1, 1),
    (86, 'Rocket engine', 'images/resources/rocket-engine.png', 1, 0, 0, 1, 1),
    (87, 'Heat shield', 'images/resources/heat-shield.png', 1, 0, 0, 1, 1),
    (88, 'Ion drive', 'images/resources/ion-drive.png', 1, 0, 0, 1, 1),
    (89, 'Jet engine', 'images/resources/jet-engine.png', 1, 0, 0, 1, 1),
    (90, 'Sub-orbital 2nd stage', 'images/resources/sub-orbital-second-stage.png', 20, 0, 0, 0, 1),
    (91, 'Sub-orbital rocket', 'images/resources/sub-orbital-rocket2.png', 20, 1, 0, 0, 1),
    (92, 'Orbital booster', 'images/resources/orbital-booster.png', 100, 0, 0, 0, 1),
    (93, 'Starship', 'images/resources/starship.png', 100, 0, 0, 0, 1),
    (94, 'BFR', 'images/resources/BFR.png', 2000, 1, 0, 0, 1),
    (95, 'Jumbo jet', 'images/resources/jumbojet2.png', 2000, 1, 0, 0, 1),
    (96, 'Luxury jet', 'images/resources/private-jet.png', 1000, 1, 0, 0, 1),
    (97, 'Single engine plane', 'images/resources/single-engine.png', 100, 1, 0, 0, 1),
    (98, 'Quadcopter', 'images/resources/quadcopter.png', 2, 1, 0, 1, 1),
    (99, 'Satellite', 'images/resources/satellite.png', 10, 1, 0, 0, 1),
    (100, 'Aerospace research', 'images/resources/aero-research.png', 0, 0, 1, 1, 1),
    (101, 'Reinforced concrete', 'images/resources/reinforced-concrete.png', 10, 0, 0, 1, 1),
    (102, 'Bricks', 'images/resources/bricks.png', 1, 1, 0, 1, 1),
    (103, 'Cement', 'images/resources/cement.png', 1, 1, 0, 1, 1),
    (104, 'Clay', 'images/resources/clay.png', 1, 0, 0, 1, 1),
    (105, 'Limestone', 'images/resources/limestone.png', 1, 0, 0, 1, 1),
    (106, 'Wood', 'images/resources/wood.png', 1, 0, 0, 1, 1),
    (107, 'Steel beams', 'images/resources/steel-beams.png', 5, 0, 0, 1, 1),
    (108, 'Planks', 'images/resources/planks.png', 1, 1, 0, 1, 1),
    (109, 'Windows', 'images/resources/windows.png', 1, 1, 0, 1, 1),
    (110, 'Tools', 'images/resources/tools.png', 1, 1, 0, 1, 1),
    (111, 'Construction units', 'images/resources/construction-units.png', 0, 0, 0, 1, 1),
    (112, 'Bulldozer', 'images/resources/bulldozer.png', 5, 0, 0, 1, 1),
    (113, 'Materials research', 'images/resources/materials-research.png', 0, 0, 1, 1, 1),
    (114, 'Robots', 'images/resources/robots.png', 2, 0, 0, 1, 1),
    (115, 'Cows', 'images/resources/cow.png', 1, 0, 0, 1, 1),
    (116, 'Pigs', 'images/resources/pig.png', 1, 0, 0, 1, 1),
    (117, 'Milk', 'images/resources/milk.png', 1, 1, 0, 1, 1),
    (118, 'Coffee beans', 'images/resources/coffee-beans.png', 0.1, 0, 0, 1, 1),
    (119, 'Coffee powder', 'images/resources/coffee-ground.png', 1, 1, 0, 1, 1),
    (120, 'Vegetables', 'images/resources/vegetables.png', 0.2, 0, 0, 1, 1),
    (121, 'Bread', 'images/resources/bread.png', 1, 1, 0, 1, 1),
    (122, 'Cheese', 'images/resources/cheese.png', 1, 1, 0, 1, 1),
    (123, 'Apple pie', 'images/resources/apple-pie.png', 2, 1, 0, 1, 1),
    (124, 'Orange juice', 'images/resources/orange-juice.png', 1, 1, 0, 1, 1),
    (125, 'Apple cider', 'images/resources/apple-cider.png', 1, 1, 0, 1, 1),
    (126, 'Ginger beer', 'images/resources/ginger-beer.png', 1, 1, 0, 1, 1),
    (127, 'Frozen pizza', 'images/resources/pizza.png', 1, 1, 0, 1, 1),
    (128, 'Pasta', 'images/resources/pasta.png', 1, 0, 0, 1, 1),
    (129, 'Hamburger', 'images/resources/hamburger.png', 2, 1, 0, 1, 1),
    (130, 'Lasagna', 'images/resources/lasagna.png', 2, 1, 0, 1, 1),
    (131, 'Meat balls', 'images/resources/meatballs.png', 2, 1, 0, 1, 1),
    (132, 'Cocktails', 'images/resources/cocktails.png', 2, 1, 0, 1, 1),
    (133, 'Flour', 'images/resources/flour.png', 0.1, 0, 0, 1, 1),
    (134, 'Butter', 'images/resources/butter.png', 1, 1, 0, 1, 1),
    (135, 'Sugar', 'images/resources/sugar.png', 1, 0, 0, 1, 1),
    (136, 'Cocoa', 'images/resources/cocoa-beans.png', 0.1, 0, 0, 1, 1),
    (137, 'Dough', 'images/resources/dough.png', 1, 0, 0, 1, 1),
    (138, 'Sauce', 'images/resources/gravy-boat.png', 2, 0, 0, 1, 1),
    (139, 'Fodder', 'images/resources/fodder.png', 1, 0, 0, 1, 1),
    (140, 'Chocolate', 'images/resources/chocolate.png', 1, 1, 0, 1, 1),
    (141, 'Vegetable oil', 'images/resources/vegetable-oil.png', 1, 0, 0, 1, 1),
    (142, 'Salad', 'images/resources/salad.png', 2, 1, 0, 1, 1),
    (143, 'Samosa', 'images/resources/samosas.png', 2, 1, 0, 1, 1),
    (144, 'Xmas ornament', 'images/resources/xmas-ornament.png', 0.5, 1, 0, 1, 1),
    (145, 'Recipes', 'images/resources/recipes.png', 0, 0, 1, 1, 1);
SET IDENTITY_INSERT resource_base OFF


SELECT *
FROM resource_base
